Contact removal
ubports/address-book-service pull request #7
Opened 2018-09-07 21:25 UTC by mardy

Fixes https://github.com/ubports/ubuntu-touch/issues/864

2018-09-09 20:44 UTC, Flohack74 requested changes

2018-09-09 20:44 UTC, Flohack74 commented on .gitignore
> +CMakeLists.txt.user
Hmmm I think there are way too many entries in this gitignore - Can you double-check this plz? Also, has no relation to the intent of the PR, does it?

2018-09-09 20:52 UTC, mardy commented on .gitignore
> +CMakeLists.txt.user
It's actually the same `.bzrignore` file we had, I just updated it (and already removed some lines).

It has not relation to the PR, and in fact I've kept it as a separate commit.

2018-09-10 14:50 UTC, NeoTheThird approved these changes
lgtm!

2018-09-10 15:00 UTC, merged